# Generated by Django 5.2.17 on 2026-09-20 23:20

import hashlib
from datetime import date

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def attach_legacy_finance_data(apps, schema_editor):
    Country = apps.get_model("finance", "Country")
    Currency = apps.get_model("finance", "Currency")
    Organization = apps.get_model("finance", "Organization")
    FiscalCalendar = apps.get_model("finance", "FiscalCalendar")
    FiscalPeriod = apps.get_model("finance", "FiscalPeriod")
    LegalEntity = apps.get_model("finance", "LegalEntity")
    GroupAccount = apps.get_model("finance", "GroupAccount")
    EntityAccount = apps.get_model("finance", "EntityAccount")
    MappingVersion = apps.get_model("finance", "MappingVersion")
    AccountMapping = apps.get_model("finance", "AccountMapping")
    Branch = apps.get_model("finance", "Branch")
    Department = apps.get_model("finance", "Department")
    Expense = apps.get_model("finance", "Expense")

    usd, _ = Currency.objects.get_or_create(
        code="USD",
        defaults={"name": "US Dollar", "symbol": "$", "decimal_places": 2},
    )
    jod, _ = Currency.objects.get_or_create(
        code="JOD",
        defaults={"name": "Jordanian Dinar", "symbol": "JD", "decimal_places": 3},
    )
    jordan, _ = Country.objects.get_or_create(
        iso_code="JO",
        defaults={
            "name": "Jordan",
            "default_currency_id": jod.id,
            "timezone": "Asia/Amman",
        },
    )

    organization, _ = Organization.objects.get_or_create(
        code="DEMO",
        defaults={
            "legal_name": "Demo Finance Organization",
            "display_name": "Demo Finance",
            "default_reporting_currency_id": usd.id,
            "timezone": "Asia/Amman",
        },
    )
    FiscalCalendar.objects.get_or_create(
        organization_id=organization.id,
        code="CAL-2026",
        defaults={"name": "Calendar 2026", "timezone": "Asia/Amman"},
    )
    calendar = FiscalCalendar.objects.get(organization_id=organization.id, code="CAL-2026")
    Organization.objects.filter(id=organization.id).update(
        default_reporting_currency_id=usd.id,
        default_fiscal_calendar_id=calendar.id,
    )
    FiscalPeriod.objects.get_or_create(
        calendar_id=calendar.id,
        code="2026",
        defaults={
            "name": "Fiscal Year 2026",
            "period_type": "year",
            "start_date": date(2026, 1, 1),
            "end_date": date(2026, 12, 31),
            "status": "open",
        },
    )
    entity, _ = LegalEntity.objects.get_or_create(
        organization_id=organization.id,
        code="DEMO-JO",
        defaults={
            "legal_name": "Demo Jordan Entity",
            "short_name": "Demo Jordan",
            "country_id": jordan.id,
            "functional_currency_id": usd.id,
            "reporting_currency_id": usd.id,
            "fiscal_calendar_id": calendar.id,
            "valid_from": date(2026, 1, 1),
            "consolidation_method": "full",
            "status": "active",
        },
    )
    group_account, _ = GroupAccount.objects.get_or_create(
        organization_id=organization.id,
        code="600000",
        defaults={
            "name": "Operating Expenses",
            "account_type": "operating_expense",
            "normal_balance": "debit",
            "level": 1,
            "is_posting_allowed": True,
            "valid_from": date(2026, 1, 1),
        },
    )
    entity_account, _ = EntityAccount.objects.get_or_create(
        legal_entity_id=entity.id,
        code="600000",
        defaults={
            "name": "Operating Expenses",
            "account_type": "operating_expense",
            "normal_balance": "debit",
            "is_posting_allowed": True,
        },
    )
    mapping_version, _ = MappingVersion.objects.get_or_create(
        organization_id=organization.id,
        code="MAP-2026-01",
        defaults={
            "name": "Initial demo account mapping",
            "valid_from": date(2026, 1, 1),
            "status": "approved",
        },
    )
    AccountMapping.objects.get_or_create(
        mapping_version_id=mapping_version.id,
        entity_account_id=entity_account.id,
        group_account_id=group_account.id,
        defaults={
            "mapping_type": "one_to_one",
            "review_status": "approved",
        },
    )

    Branch.objects.all().update(legal_entity_id=entity.id, country_id=jordan.id)
    Department.objects.all().update(legal_entity_id=entity.id, is_active=True)
    for expense in Expense.objects.select_related("department__branch").all():
        branch_id = expense.department.branch_id
        source_record_id = str(expense.id)
        hash_input = "|".join(
            [
                "django",
                "finance_expense",
                source_record_id,
                str(expense.amount),
                expense.currency,
                expense.expense_date.isoformat(),
                expense.description,
            ]
        )
        expense.branch_id = branch_id
        expense.legal_entity_id = entity.id
        expense.entity_account_id = entity_account.id
        expense.group_account_id = group_account.id
        expense.currency_master_id = usd.id
        expense.source_record_id = source_record_id
        expense.source_created_at = expense.created_at
        expense.source_updated_at = expense.updated_at
        expense.record_hash = hashlib.sha256(hash_input.encode("utf-8")).hexdigest()
        expense.save(
            update_fields=[
                "branch",
                "legal_entity",
                "entity_account",
                "group_account",
                "currency_master",
                "source_record_id",
                "source_created_at",
                "source_updated_at",
                "record_hash",
                "updated_at",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iso_code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('tax_jurisdiction_code', models.CharField(blank=True, max_length=40)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
            ],
            options={
                'ordering': ['iso_code'],
            },
        ),
        migrations.CreateModel(
            name='FiscalCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['organization_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(max_length=80)),
                ('source_entity', models.CharField(max_length=120)),
                ('strategy', models.CharField(choices=[('cursor', 'Cursor'), ('snapshot', 'Snapshot'), ('append_only', 'Append only'), ('full_refresh', 'Full refresh')], max_length=16)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('partial', 'Partial')], default='running', max_length=16)),
                ('external_run_id', models.CharField(blank=True, max_length=120)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_read', models.PositiveIntegerField(default=0)),
                ('records_inserted', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('records_skipped', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MappingVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], default='pending', max_length=16)),
            ],
            options={
                'ordering': ['organization_id', 'valid_from', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OwnershipPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('control_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('consolidation_method', models.CharField(choices=[('full', 'Full consolidation'), ('equity', 'Equity method'), ('proportional', 'Proportional consolidation'), ('excluded', 'Excluded')], max_length=20)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['child_entity_id', 'valid_from'],
            },
        ),
        migrations.CreateModel(
            name='ProfitCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['legal_entity_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=160)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=16)),
            ],
            options={
                'ordering': ['legal_entity_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RawExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(max_length=80)),
                ('source_entity', models.CharField(max_length=120)),
                ('source_record_id', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('expense_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('source_account_code', models.CharField(blank=True, max_length=80)),
                ('source_branch_code', models.CharField(blank=True, max_length=80)),
                ('source_department_code', models.CharField(blank=True, max_length=80)),
                ('source_cost_center_code', models.CharField(blank=True, max_length=80)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('record_hash', models.CharField(max_length=128)),
                ('is_deleted', models.BooleanField(default=False)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['expense_date', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['expense_date', 'id']},
        ),
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.AddField(
            model_name='branch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='finance.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.branch'),
        ),
        migrations.AddField(
            model_name='expense',
            name='ingested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='record_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='expense',
            name='source_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='source_entity',
            field=models.CharField(default='finance_expense', max_length=120),
        ),
        migrations.AddField(
            model_name='expense',
            name='source_record_id',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='source_system',
            field=models.CharField(default='django', max_length=80),
        ),
        migrations.AddField(
            model_name='expense',
            name='source_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='finance.branch'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='department',
                    name='code',
                    field=models.CharField(max_length=40),
                ),
                migrations.AlterField(
                    model_name='expense',
                    name='amount',
                    field=models.DecimalField(decimal_places=2, max_digits=18),
                ),
            ],
        ),
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='draft', max_length=16)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_budget_plans', to=settings.AUTH_USER_MODEL)),
                ('fiscal_calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_plans', to='finance.fiscalcalendar')),
            ],
            options={
                'ordering': ['organization_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BudgetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=160)),
                ('version_type', models.CharField(choices=[('original', 'Original budget'), ('revised', 'Revised budget'), ('forecast', 'Forecast')], max_length=16)),
                ('scenario', models.CharField(default='BASE', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='draft', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budget_versions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='finance.budgetplan')),
            ],
            options={
                'ordering': ['plan_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_business_units', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='finance.businessunit')),
            ],
            options={
                'ordering': ['organization_id', 'code'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.businessunit'),
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_centers', to='finance.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_centers', to='finance.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cost_centers', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='finance.costcenter')),
            ],
            options={
                'ordering': ['legal_entity_id', 'code'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.costcenter'),
        ),
        migrations.AddField(
            model_name='branch',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='finance.country'),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('symbol', models.CharField(blank=True, max_length=8)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('decimal_places__gte', 0), ('decimal_places__lte', 4)), name='currency_decimal_places_range')],
            },
        ),
        migrations.AddField(
            model_name='country',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='finance.currency'),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.currency'),
        ),
        migrations.CreateModel(
            name='DepartmentBranchAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_assignments', to='finance.branch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_assignments', to='finance.department')),
            ],
        ),
        migrations.CreateModel(
            name='EntityAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=160)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('cost_of_sales', 'Cost of sales'), ('operating_expense', 'Operating expense'), ('other_income', 'Other income'), ('other_expense', 'Other expense'), ('tax', 'Tax'), ('statistical', 'Statistical')], max_length=24)),
                ('normal_balance', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=8)),
                ('is_posting_allowed', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='finance.entityaccount')),
            ],
            options={
                'ordering': ['legal_entity_id', 'code'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='entity_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.entityaccount'),
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('period_type', models.CharField(choices=[('month', 'Month'), ('quarter', 'Quarter'), ('year', 'Year')], max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('soft_closed', 'Soft closed'), ('closed', 'Closed')], default='open', max_length=16)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='finance.fiscalcalendar')),
            ],
            options={
                'ordering': ['start_date', 'code'],
            },
        ),
        migrations.CreateModel(
            name='GroupAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=160)),
                ('localized_name', models.CharField(blank=True, max_length=160)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('cost_of_sales', 'Cost of sales'), ('operating_expense', 'Operating expense'), ('other_income', 'Other income'), ('other_expense', 'Other expense'), ('tax', 'Tax'), ('statistical', 'Statistical')], max_length=24)),
                ('normal_balance', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=8)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('is_posting_allowed', models.BooleanField(default=True)),
                ('is_control_account', models.BooleanField(default=False)),
                ('requires_cost_center', models.BooleanField(default=False)),
                ('requires_project', models.BooleanField(default=False)),
                ('requires_intercompany', models.BooleanField(default=False)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='finance.groupaccount')),
            ],
            options={
                'ordering': ['organization_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapping_type', models.CharField(choices=[('one_to_one', 'One to one'), ('many_to_one', 'Many to one'), ('one_to_many', 'One to many'), ('manual_adjustment', 'Manual adjustment'), ('unmapped', 'Unmapped')], max_length=24)),
                ('allocation_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_account_mappings', to=settings.AUTH_USER_MODEL)),
                ('entity_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_mappings', to='finance.entityaccount')),
                ('group_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_mappings', to='finance.groupaccount')),
            ],
            options={
                'ordering': ['entity_account_id', 'group_account_id'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='group_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.groupaccount'),
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('legal_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=120)),
                ('tax_registration_number', models.CharField(blank=True, max_length=100)),
                ('consolidation_method', models.CharField(choices=[('full', 'Full consolidation'), ('equity', 'Equity method'), ('proportional', 'Proportional consolidation'), ('excluded', 'Excluded')], default='full', max_length=20)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legal_entities', to='finance.country')),
                ('fiscal_calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_entities', to='finance.fiscalcalendar')),
                ('functional_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='functional_entities', to='finance.currency')),
                ('parent_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_entities', to='finance.legalentity')),
                ('reporting_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reporting_entities', to='finance.currency')),
            ],
            options={
                'ordering': ['organization_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EntityBusinessUnitAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_assignments', to='finance.businessunit')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_unit_assignments', to='finance.legalentity')),
            ],
        ),
        migrations.AddField(
            model_name='entityaccount',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_accounts', to='finance.legalentity'),
        ),
        migrations.CreateModel(
            name='DepartmentEntityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_assignments', to='finance.department')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_assignments', to='finance.legalentity')),
            ],
        ),
        migrations.AddField(
            model_name='costcenter',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='finance.legalentity'),
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='finance.branch')),
                ('budget_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_budget_lines', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='finance.department')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.budgetversion')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='finance.businessunit')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='finance.costcenter')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='finance.currency')),
                ('entity_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='finance.entityaccount')),
                ('fiscal_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='finance.fiscalperiod')),
                ('group_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='finance.groupaccount')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='finance.legalentity')),
            ],
            options={
                'ordering': ['fiscal_period_id', 'legal_entity_id', 'group_account_id'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='finance.legalentity'),
        ),
        migrations.AddField(
            model_name='department',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='finance.legalentity'),
        ),
        migrations.AddField(
            model_name='expense',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.legalentity'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(condition=models.Q(('legal_entity__isnull', False)), fields=('legal_entity', 'code'), name='uniq_branch_code_entity'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('branch', 'code'), name='uniq_department_code_branch'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True), ('legal_entity__isnull', False)), fields=('legal_entity', 'code'), name='uniq_department_code_entity'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.CheckConstraint(condition=models.Q(('branch__isnull', False), ('legal_entity__isnull', False), _connector='OR'), name='department_has_scope'),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='mapping_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_mappings', to='finance.mappingversion'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_fiscal_calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_for_organizations', to='finance.fiscalcalendar'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_reporting_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reporting_organizations', to='finance.currency'),
        ),
        migrations.AddField(
            model_name='mappingversion',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_versions', to='finance.organization'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_entities', to='finance.organization'),
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_runs', to='finance.organization'),
        ),
        migrations.AddField(
            model_name='groupaccount',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_accounts', to='finance.organization'),
        ),
        migrations.AddField(
            model_name='fiscalcalendar',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_calendars', to='finance.organization'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_units', to='finance.organization'),
        ),
        migrations.AddField(
            model_name='budgetplan',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_plans', to='finance.organization'),
        ),
        migrations.AddField(
            model_name='ownershipperiod',
            name='child_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_records', to='finance.legalentity'),
        ),
        migrations.AddField(
            model_name='ownershipperiod',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_periods', to='finance.organization'),
        ),
        migrations.AddField(
            model_name='ownershipperiod',
            name='parent_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_interests', to='finance.legalentity'),
        ),
        migrations.AddField(
            model_name='profitcenter',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profit_centers', to='finance.branch'),
        ),
        migrations.AddField(
            model_name='profitcenter',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profit_centers', to='finance.businessunit'),
        ),
        migrations.AddField(
            model_name='profitcenter',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_centers', to='finance.legalentity'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='profit_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='finance.profitcenter'),
        ),
        migrations.AddField(
            model_name='expense',
            name='profit_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.profitcenter'),
        ),
        migrations.AddField(
            model_name='project',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='finance.businessunit'),
        ),
        migrations.AddField(
            model_name='project',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='finance.legalentity'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='finance.project'),
        ),
        migrations.AddField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.project'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_date'], name='finance_exp_expense_a60cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['legal_entity', 'expense_date'], name='finance_exp_legal_e_00f8f7_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['source_system', 'source_entity', 'source_updated_at'], name='finance_exp_source__fb14ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('source_record_id__isnull', False)), fields=('source_system', 'source_entity', 'source_record_id'), name='uniq_expense_source_record'),
        ),
        migrations.AddField(
            model_name='rawexpense',
            name='ingestion_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_expenses', to='finance.ingestionrun'),
        ),
        migrations.AddConstraint(
            model_name='budgetversion',
            constraint=models.UniqueConstraint(fields=('plan', 'code'), name='uniq_budget_version_code_plan'),
        ),
        migrations.AddConstraint(
            model_name='departmentbranchassignment',
            constraint=models.UniqueConstraint(fields=('department', 'branch', 'valid_from'), name='uniq_department_branch_start'),
        ),
        migrations.AddConstraint(
            model_name='departmentbranchassignment',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='department_branch_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='fiscalperiod',
            constraint=models.UniqueConstraint(fields=('calendar', 'code'), name='uniq_fiscal_period_code_calendar'),
        ),
        migrations.AddConstraint(
            model_name='fiscalperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='fiscal_period_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='entitybusinessunitassignment',
            constraint=models.UniqueConstraint(fields=('legal_entity', 'business_unit', 'valid_from'), name='uniq_entity_business_unit_start'),
        ),
        migrations.AddConstraint(
            model_name='entitybusinessunitassignment',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='entity_business_unit_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='entityaccount',
            constraint=models.UniqueConstraint(fields=('legal_entity', 'code'), name='uniq_entity_account_code'),
        ),
        migrations.AddConstraint(
            model_name='departmententityassignment',
            constraint=models.UniqueConstraint(fields=('department', 'legal_entity', 'valid_from'), name='uniq_department_entity_start'),
        ),
        migrations.AddConstraint(
            model_name='departmententityassignment',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='department_entity_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.UniqueConstraint(fields=('legal_entity', 'code'), name='uniq_cost_center_code_entity'),
        ),
        migrations.AddConstraint(
            model_name='accountmapping',
            constraint=models.UniqueConstraint(fields=('mapping_version', 'entity_account', 'group_account'), name='uniq_account_mapping_rule'),
        ),
        migrations.AddConstraint(
            model_name='accountmapping',
            constraint=models.CheckConstraint(condition=models.Q(('allocation_percentage__isnull', True), models.Q(('allocation_percentage__gte', 0), ('allocation_percentage__lte', 100)), _connector='OR'), name='account_mapping_allocation_range'),
        ),
        migrations.AddConstraint(
            model_name='mappingversion',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_mapping_version_code_org'),
        ),
        migrations.AddConstraint(
            model_name='mappingversion',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='mapping_version_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='legalentity',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_legal_entity_code_org'),
        ),
        migrations.AddConstraint(
            model_name='legalentity',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='legal_entity_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='legalentity',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('parent_entity_id')), _negated=True), name='legal_entity_not_own_parent'),
        ),
        migrations.AddConstraint(
            model_name='ingestionrun',
            constraint=models.UniqueConstraint(condition=models.Q(('external_run_id', ''), _negated=True), fields=('source_system', 'external_run_id'), name='uniq_ingestion_external_run'),
        ),
        migrations.AddConstraint(
            model_name='ingestionrun',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='ingestion_finished_after_started'),
        ),
        migrations.AddConstraint(
            model_name='groupaccount',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_group_account_code_org'),
        ),
        migrations.AddConstraint(
            model_name='groupaccount',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1)), name='group_account_level_positive'),
        ),
        migrations.AddConstraint(
            model_name='groupaccount',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='group_account_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='fiscalcalendar',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_fiscal_calendar_code_org'),
        ),
        migrations.AddConstraint(
            model_name='businessunit',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_business_unit_code_org'),
        ),
        migrations.AddConstraint(
            model_name='businessunit',
            constraint=models.CheckConstraint(condition=models.Q(('parent__isnull', True), models.Q(('id', models.F('parent_id')), _negated=True), _connector='OR'), name='business_unit_not_own_parent'),
        ),
        migrations.AddConstraint(
            model_name='budgetplan',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_budget_plan_code_org'),
        ),
        migrations.AddConstraint(
            model_name='ownershipperiod',
            constraint=models.CheckConstraint(condition=models.Q(('ownership_percentage__gte', 0), ('ownership_percentage__lte', 100)), name='ownership_percentage_range'),
        ),
        migrations.AddConstraint(
            model_name='ownershipperiod',
            constraint=models.CheckConstraint(condition=models.Q(('control_percentage__isnull', True), models.Q(('control_percentage__gte', 0), ('control_percentage__lte', 100)), _connector='OR'), name='control_percentage_range'),
        ),
        migrations.AddConstraint(
            model_name='ownershipperiod',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='ownership_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='ownershipperiod',
            constraint=models.CheckConstraint(condition=models.Q(('parent_entity', models.F('child_entity')), _negated=True), name='ownership_entities_distinct'),
        ),
        migrations.AddConstraint(
            model_name='profitcenter',
            constraint=models.UniqueConstraint(fields=('legal_entity', 'code'), name='uniq_profit_center_code_entity'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('legal_entity', 'code'), name='uniq_project_code_entity'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='project_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.UniqueConstraint(fields=('version', 'legal_entity', 'fiscal_period', 'group_account', 'entity_account', 'branch', 'department', 'cost_center', 'profit_center', 'business_unit', 'project'), name='uniq_budget_line_grain', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='rawexpense',
            index=models.Index(fields=['source_system', 'source_entity', 'source_updated_at'], name='finance_raw_source__7b77fd_idx'),
        ),
        migrations.AddIndex(
            model_name='rawexpense',
            index=models.Index(fields=['record_hash'], name='finance_raw_record__5c4f3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='rawexpense',
            constraint=models.UniqueConstraint(fields=('source_system', 'source_entity', 'source_record_id'), name='uniq_raw_expense_source_record'),
        ),
        migrations.RunPython(attach_legacy_finance_data, migrations.RunPython.noop),
    ]
