# Generated by Django 5.2.17 on 2026-09-20 23:47

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_allocationrule_allocationruleline_approvalrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionrun',
            name='error_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_ingestion_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ImportSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('protocol', models.CharField(choices=[('csv', 'CSV/Excel upload'), ('sftp', 'SFTP file drop'), ('api', 'REST API'), ('db', 'Direct database link')], max_length=8)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('secret_ref', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_sources', to='finance.organization')),
            ],
            options={
                'ordering': ['organization_id', 'name'],
            },
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='import_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_runs', to='finance.importsource'),
        ),
        migrations.CreateModel(
            name='IngestionIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error')], default='error', max_length=8)),
                ('source_entity', models.CharField(max_length=120)),
                ('source_record_id', models.CharField(blank=True, max_length=160)),
                ('source_line_id', models.CharField(blank=True, max_length=160)),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('code', models.CharField(max_length=80)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ingestion_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='finance.ingestionrun')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_ingestion_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewCodeDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_type', models.CharField(choices=[('account', 'Account'), ('legal_entity', 'Legal entity'), ('branch', 'Branch'), ('department', 'Department'), ('cost_center', 'Cost center'), ('profit_center', 'Profit center'), ('business_unit', 'Business unit'), ('project', 'Project')], max_length=16)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('linked', 'Linked'), ('created', 'Created'), ('rejected', 'Rejected')], default='pending', max_length=8)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('ingestion_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discovered_codes', to='finance.ingestionrun')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discovered_source_codes', to='finance.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_source_code_discoveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawJournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(max_length=80)),
                ('source_entity', models.CharField(max_length=120)),
                ('source_record_id', models.CharField(max_length=160)),
                ('source_line_id', models.CharField(max_length=160)),
                ('source_legal_entity_code', models.CharField(blank=True, max_length=80)),
                ('document_number', models.CharField(blank=True, max_length=160)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('posting_date', models.DateField()),
                ('document_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('source_account_code', models.CharField(max_length=80)),
                ('source_branch_code', models.CharField(blank=True, max_length=80)),
                ('source_department_code', models.CharField(blank=True, max_length=80)),
                ('source_cost_center_code', models.CharField(blank=True, max_length=80)),
                ('source_profit_center_code', models.CharField(blank=True, max_length=80)),
                ('source_business_unit_code', models.CharField(blank=True, max_length=80)),
                ('source_project_code', models.CharField(blank=True, max_length=80)),
                ('source_counterparty_code', models.CharField(blank=True, max_length=80)),
                ('currency', models.CharField(max_length=3)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('reporting_currency', models.CharField(blank=True, max_length=3)),
                ('reporting_debit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('reporting_credit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('record_hash', models.CharField(max_length=128)),
                ('is_deleted', models.BooleanField(default=False)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('ingestion_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_journal_lines', to='finance.ingestionrun')),
            ],
            options={
                'ordering': ['posting_date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='importsource',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_import_source_name_org'),
        ),
        migrations.AddIndex(
            model_name='ingestionissue',
            index=models.Index(fields=['ingestion_run', 'severity'], name='finance_ing_ingesti_f26669_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionissue',
            index=models.Index(fields=['ingestion_run', 'source_record_id'], name='finance_ing_ingesti_08933d_idx'),
        ),
        migrations.AddIndex(
            model_name='newcodediscovery',
            index=models.Index(fields=['organization', 'code_type', 'code'], name='finance_new_organiz_b31608_idx'),
        ),
        migrations.AddIndex(
            model_name='newcodediscovery',
            index=models.Index(fields=['status'], name='finance_new_status_3f6c94_idx'),
        ),
        migrations.AddConstraint(
            model_name='newcodediscovery',
            constraint=models.UniqueConstraint(fields=('ingestion_run', 'code_type', 'code'), name='uniq_discovered_code_per_run'),
        ),
        migrations.AddIndex(
            model_name='rawjournalline',
            index=models.Index(fields=['ingestion_run', 'posting_date'], name='finance_raw_ingesti_7bc006_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjournalline',
            index=models.Index(fields=['source_system', 'source_entity', 'source_updated_at'], name='finance_raw_source__117c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjournalline',
            index=models.Index(fields=['record_hash'], name='finance_raw_record__8bd26b_idx'),
        ),
        migrations.AddConstraint(
            model_name='rawjournalline',
            constraint=models.UniqueConstraint(fields=('source_system', 'source_entity', 'source_record_id', 'source_line_id'), name='uniq_raw_journal_line_source_record'),
        ),
        migrations.AddConstraint(
            model_name='rawjournalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit_amount__gt', 0), ('credit_amount', 0)), models.Q(('debit_amount', 0), ('credit_amount__gt', 0)), _connector='OR'), name='raw_journal_line_one_sided_amount'),
        ),
    ]
