# Generated by Django 5.2.17 on 2026-09-20 23:53

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_ingestionrun_error_log_ingestionrun_triggered_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], default='pending', max_length=16)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_hierarchies', to='finance.organization')),
            ],
            options={
                'ordering': ['organization_id', 'code', 'version'],
            },
        ),
        migrations.CreateModel(
            name='AccountHierarchyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_code', models.CharField(blank=True, max_length=80)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('is_subtotal', models.BooleanField(default=False)),
                ('sign_multiplier', models.SmallIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('group_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hierarchy_nodes', to='finance.groupaccount')),
                ('hierarchy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='finance.accounthierarchy')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.accounthierarchynode')),
            ],
            options={
                'ordering': ['hierarchy_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConsolidationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidation_groups', to='finance.organization')),
                ('parent_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consolidation_groups', to='finance.legalentity')),
                ('reporting_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consolidation_groups', to='finance.currency')),
            ],
            options={
                'ordering': ['organization_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ConsolidationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_set', models.CharField(choices=[('actuals', 'Actuals'), ('planning', 'Planning scenario')], max_length=10)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('fiscal_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consolidation_runs', to='finance.fiscalperiod')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='finance.consolidationgroup')),
                ('scenario_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consolidation_runs', to='finance.budgetversion')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consolidation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsolidationScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='finance.consolidationgroup')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consolidation_scopes', to='finance.legalentity')),
            ],
            options={
                'ordering': ['group_id', 'valid_from', 'legal_entity_id'],
            },
        ),
        migrations.CreateModel(
            name='EliminationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('account_at_entity_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elimination_rules_as_a', to='finance.groupaccount')),
                ('account_at_entity_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elimination_rules_as_b', to='finance.groupaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elimination_rules', to='finance.organization')),
            ],
            options={
                'ordering': ['organization_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EliminationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('group_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elimination_entries', to='finance.groupaccount')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elimination_entries', to='finance.legalentity')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elimination_entries', to='finance.consolidationrun')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='finance.eliminationrule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodwillCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('net_assets_at_acquisition', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goodwill_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amortisation_years', models.PositiveIntegerField(default=10)),
                ('acquisition_date', models.DateField()),
                ('amortisation_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goodwill_amortisation_calculations', to='finance.groupaccount')),
                ('goodwill_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goodwill_calculations', to='finance.groupaccount')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goodwill_calculations', to='finance.legalentity')),
            ],
        ),
        migrations.CreateModel(
            name='IntercompanyInventoryElimination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intercompany_inventory_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('profit_margin_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unrealised_profit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('buying_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_purchase_eliminations', to='finance.legalentity')),
                ('cogs_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_cogs_eliminations', to='finance.groupaccount')),
                ('inventory_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_eliminations', to='finance.groupaccount')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_eliminations', to='finance.consolidationrun')),
                ('selling_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_sales_eliminations', to='finance.legalentity')),
            ],
        ),
        migrations.CreateModel(
            name='IntercompanyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entity_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intercompany_pairs_as_a', to='finance.legalentity')),
                ('entity_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intercompany_pairs_as_b', to='finance.legalentity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercompany_pairs', to='finance.organization')),
            ],
            options={
                'ordering': ['organization_id', 'entity_a_id', 'entity_b_id'],
            },
        ),
        migrations.CreateModel(
            name='IntercompanyMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_entity_a', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('amount_entity_b', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('problem', 'Amount mismatch'), ('unknown', 'Counterpart not found')], default='unknown', max_length=10)),
                ('no_part', models.BooleanField(default=False)),
                ('manual_correction', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('matched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='finance.eliminationrule')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercompany_matches', to='finance.consolidationrun')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='finance.intercompanypair')),
            ],
        ),
        migrations.CreateModel(
            name='MinorityInterestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pre_minority_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('minority_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minority_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('group_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='minority_entries', to='finance.groupaccount')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='minority_entries', to='finance.legalentity')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minority_entries', to='finance.consolidationrun')),
            ],
        ),
        migrations.CreateModel(
            name='TranslationAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('rate_used', models.DecimalField(decimal_places=8, max_digits=18)),
                ('translated_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cta_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('group_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translation_entries', to='finance.groupaccount')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translation_entries', to='finance.legalentity')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_entries', to='finance.consolidationrun')),
            ],
        ),
        migrations.AddConstraint(
            model_name='accounthierarchy',
            constraint=models.UniqueConstraint(fields=('organization', 'code', 'version'), name='uniq_account_hierarchy_version'),
        ),
        migrations.AddConstraint(
            model_name='accounthierarchy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('is_active', True)), fields=('organization',), name='uniq_active_default_account_hierarchy'),
        ),
        migrations.AddConstraint(
            model_name='accounthierarchy',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='account_hierarchy_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='accounthierarchy',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='account_hierarchy_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='accounthierarchynode',
            constraint=models.UniqueConstraint(condition=models.Q(('node_code', ''), _negated=True), fields=('hierarchy', 'node_code'), name='uniq_account_hierarchy_node_code'),
        ),
        migrations.AddConstraint(
            model_name='accounthierarchynode',
            constraint=models.CheckConstraint(condition=models.Q(('sign_multiplier', 1), ('sign_multiplier', -1), _connector='OR'), name='account_hierarchy_sign_multiplier'),
        ),
        migrations.AddConstraint(
            model_name='accounthierarchynode',
            constraint=models.CheckConstraint(condition=models.Q(('parent__isnull', True), models.Q(('id', models.F('parent_id')), _negated=True), _connector='OR'), name='account_hierarchy_node_not_own_parent'),
        ),
        migrations.AddConstraint(
            model_name='consolidationgroup',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_consolidation_group_code_org'),
        ),
        migrations.AddConstraint(
            model_name='consolidationrun',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__isnull', True), ('completed_at__gte', models.F('started_at')), _connector='OR'), name='consolidation_completed_after_started'),
        ),
        migrations.AddConstraint(
            model_name='consolidationscope',
            constraint=models.UniqueConstraint(fields=('group', 'legal_entity', 'valid_from'), name='uniq_consolidation_scope_start'),
        ),
        migrations.AddConstraint(
            model_name='consolidationscope',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='consolidation_scope_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='eliminationrule',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_elimination_rule_code_org'),
        ),
        migrations.AddConstraint(
            model_name='goodwillcalculation',
            constraint=models.CheckConstraint(condition=models.Q(('ownership_percentage__gte', 0), ('ownership_percentage__lte', 100)), name='goodwill_ownership_percentage_range'),
        ),
        migrations.AddConstraint(
            model_name='goodwillcalculation',
            constraint=models.CheckConstraint(condition=models.Q(('amortisation_years__gte', 1)), name='goodwill_amortisation_years_positive'),
        ),
        migrations.AddConstraint(
            model_name='intercompanyinventoryelimination',
            constraint=models.CheckConstraint(condition=models.Q(('profit_margin_percentage__gte', 0), ('profit_margin_percentage__lte', 100)), name='inventory_profit_margin_range'),
        ),
        migrations.AddConstraint(
            model_name='intercompanyinventoryelimination',
            constraint=models.CheckConstraint(condition=models.Q(('selling_entity', models.F('buying_entity')), _negated=True), name='inventory_elimination_distinct_entities'),
        ),
        migrations.AddConstraint(
            model_name='intercompanypair',
            constraint=models.UniqueConstraint(fields=('organization', 'entity_a', 'entity_b'), name='uniq_intercompany_pair'),
        ),
        migrations.AddConstraint(
            model_name='intercompanypair',
            constraint=models.CheckConstraint(condition=models.Q(('entity_a', models.F('entity_b')), _negated=True), name='intercompany_pair_distinct_entities'),
        ),
        migrations.AddConstraint(
            model_name='intercompanymatch',
            constraint=models.UniqueConstraint(fields=('run', 'pair', 'rule'), name='uniq_intercompany_match'),
        ),
        migrations.AddConstraint(
            model_name='minorityinterestentry',
            constraint=models.CheckConstraint(condition=models.Q(('minority_percentage__gte', 0), ('minority_percentage__lte', 100)), name='minority_percentage_range'),
        ),
        migrations.AddConstraint(
            model_name='translationadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('rate_used__gt', 0)), name='translation_rate_positive'),
        ),
    ]
