# Generated by Django 5.2.17 on 2026-09-21 00:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_accounthierarchy_accounthierarchynode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRuleDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalculationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanningFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_kind', models.CharField(choices=[('input', 'Manual input'), ('calculated', 'Calculated'), ('allocated', 'Allocated'), ('imported', 'Imported')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('lineage', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['fiscal_period_id', 'legal_entity_id', 'group_account_id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['organization_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=160)),
                ('scenario_type', models.CharField(choices=[('budget', 'Budget'), ('forecast', 'Forecast'), ('rolling_forecast', 'Rolling forecast'), ('best_case', 'Best case'), ('worst_case', 'Worst case'), ('simulation', 'Simulation')], max_length=24)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['organization_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioBlend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_kind', models.CharField(choices=[('actuals', 'Actuals'), ('planning', 'Planning scenario')], max_length=16)),
                ('priority', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['result_version_id', 'priority', 'fiscal_period_from_id'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=160)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('approved', 'Approved'), ('locked', 'Locked'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('is_final', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['scenario_id', 'version_number'],
            },
        ),
        migrations.CreateModel(
            name='UserOrgScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['user_id', 'organization_id', 'valid_from'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='drivervalue',
            name='uniq_driver_value_scope',
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='rule_type',
            field=models.CharField(choices=[('driver', 'Driver'), ('allocation', 'Allocation'), ('account_to_account', 'Account to account'), ('growth', 'Growth'), ('spread', 'Spread'), ('fx', 'Foreign exchange')], default='driver', max_length=24),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='is_open_for_actuals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='is_open_for_planning',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate_type',
            field=models.CharField(choices=[('spot', 'Spot'), ('average', 'Average'), ('closing', 'Closing'), ('budget', 'Budget')], default='spot', max_length=16),
        ),
        migrations.AddField(
            model_name='calculationruledependency',
            name='depends_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependent_rules', to='finance.calculationrule'),
        ),
        migrations.AddField(
            model_name='calculationruledependency',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='finance.calculationrule'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculation_runs', to='finance.organization'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_calculation_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planningfact',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planning_facts', to='finance.branch'),
        ),
        migrations.AddField(
            model_name='planningfact',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planning_facts', to='finance.businessunit'),
        ),
        migrations.AddField(
            model_name='planningfact',
            name='calculation_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='finance.calculationrun'),
        ),
        migrations.AddField(
            model_name='planningfact',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planning_facts', to='finance.costcenter'),
        ),
        migrations.AddField(
            model_name='planningfact',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_facts', to='finance.currency'),
        ),
        migrations.AddField(
            model_name='planningfact',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planning_facts', to='finance.department'),
        ),
        migrations.AddField(
            model_name='planningfact',
            name='entity_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planning_facts', to='finance.entityaccount'),
        ),
        migrations.AddField(
            model_name='planningfact',
            name='fiscal_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_facts', to='finance.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='planningfact',
            name='group_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_facts', to='finance.groupaccount'),
        ),
        migrations.AddField(
            model_name='planningfact',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_facts', to='finance.legalentity'),
        ),
        migrations.AddField(
            model_name='planningfact',
            name='profit_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planning_facts', to='finance.profitcenter'),
        ),
        migrations.AddField(
            model_name='planningfact',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planning_facts', to='finance.project'),
        ),
        migrations.AddField(
            model_name='planningfact',
            name='source_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planning_facts', to='finance.calculationrule'),
        ),
        migrations.AddField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='finance.organization'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_scenarios', to='finance.organization'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_planning_scenarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scenarioblend',
            name='fiscal_period_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenario_blends_from', to='finance.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='scenarioblend',
            name='fiscal_period_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenario_blends_to', to='finance.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='scenarioversion',
            name='based_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_versions', to='finance.scenarioversion'),
        ),
        migrations.AddField(
            model_name='scenarioversion',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_scenario_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scenarioversion',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='finance.scenario'),
        ),
        migrations.AddField(
            model_name='scenarioblend',
            name='result_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blend_components', to='finance.scenarioversion'),
        ),
        migrations.AddField(
            model_name='scenarioblend',
            name='source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blend_usages', to='finance.scenarioversion'),
        ),
        migrations.AddField(
            model_name='planningfact',
            name='scenario_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_facts', to='finance.scenarioversion'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='scenario_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculation_runs', to='finance.scenarioversion'),
        ),
        migrations.AddField(
            model_name='budgetversion',
            name='scenario_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_versions', to='finance.scenarioversion'),
        ),
        migrations.AddField(
            model_name='calculationrule',
            name='scenario_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculation_rules', to='finance.scenarioversion'),
        ),
        migrations.AddField(
            model_name='drivervalue',
            name='scenario_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver_values', to='finance.scenarioversion'),
        ),
        migrations.AddConstraint(
            model_name='drivervalue',
            constraint=models.UniqueConstraint(fields=('driver', 'scenario_version', 'fiscal_period', 'legal_entity', 'branch', 'department', 'project'), name='uniq_driver_value_scenario_scope', nulls_distinct=False),
        ),
        migrations.AddField(
            model_name='userorgscope',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_scopes', to='finance.branch'),
        ),
        migrations.AddField(
            model_name='userorgscope',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_scopes', to='finance.department'),
        ),
        migrations.AddField(
            model_name='userorgscope',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_scopes', to='finance.legalentity'),
        ),
        migrations.AddField(
            model_name='userorgscope',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scopes', to='finance.organization'),
        ),
        migrations.AddField(
            model_name='userorgscope',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_scopes', to='finance.role'),
        ),
        migrations.AddField(
            model_name='userorgscope',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_scopes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='calculationruledependency',
            constraint=models.UniqueConstraint(fields=('rule', 'depends_on'), name='uniq_calculation_rule_dependency'),
        ),
        migrations.AddConstraint(
            model_name='calculationruledependency',
            constraint=models.CheckConstraint(condition=models.Q(('rule', models.F('depends_on')), _negated=True), name='calculation_rule_dependency_not_self'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_role_code_org'),
        ),
        migrations.AddConstraint(
            model_name='scenario',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_scenario_code_org'),
        ),
        migrations.AddConstraint(
            model_name='scenarioversion',
            constraint=models.UniqueConstraint(fields=('scenario', 'code'), name='uniq_scenario_version_code'),
        ),
        migrations.AddConstraint(
            model_name='scenarioversion',
            constraint=models.UniqueConstraint(fields=('scenario', 'version_number'), name='uniq_scenario_version_number'),
        ),
        migrations.AddConstraint(
            model_name='scenarioversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='scenario_version_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='scenarioblend',
            constraint=models.UniqueConstraint(fields=('result_version', 'source_kind', 'source_version', 'fiscal_period_from', 'fiscal_period_to', 'priority'), name='uniq_scenario_blend_component', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='planningfact',
            constraint=models.UniqueConstraint(fields=('calculation_run', 'scenario_version', 'fiscal_period', 'legal_entity', 'group_account', 'entity_account', 'branch', 'department', 'cost_center', 'profit_center', 'business_unit', 'project'), name='uniq_planning_fact_grain', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='calculationrun',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__isnull', True), ('completed_at__gte', models.F('started_at')), _connector='OR'), name='calculation_completed_after_started'),
        ),
        migrations.AddConstraint(
            model_name='userorgscope',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'organization', 'legal_entity', 'branch', 'department', 'valid_from'), name='uniq_user_org_scope', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='userorgscope',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='user_org_scope_valid_dates'),
        ),
    ]
