# Generated by Django 5.2.17 on 2026-09-21 00:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalaction',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions', to='finance.workflowstep'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_approval_requests', to='finance.workflowstep'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='required_role_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_steps', to='finance.role'),
        ),
        migrations.CreateModel(
            name='ReportColumnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('model_type', models.CharField(choices=[('analysis', 'Analysis report'), ('monthly', 'Monthly report')], default='monthly', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('is_shared', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_column_models', to='finance.organization')),
            ],
            options={
                'ordering': ['organization_id', 'model_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportColumnModelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('label_prefix', models.CharField(max_length=64)),
                ('data_type', models.CharField(choices=[('actuals', 'Actuals'), ('scenario', 'Scenario/version'), ('mixed', 'Actuals plus scenario')], max_length=16)),
                ('relative_period_offset', models.IntegerField(blank=True, null=True)),
                ('period_from_offset', models.IntegerField(default=0)),
                ('period_to_offset', models.IntegerField(default=0)),
                ('prior_year', models.BooleanField(default=False)),
                ('column_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.reportcolumnmodel')),
                ('mixed_cutover_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mixed_report_column_model_items', to='finance.fiscalperiod')),
                ('scenario_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_column_model_items', to='finance.scenarioversion')),
            ],
            options={
                'ordering': ['column_model_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_groups', to='finance.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.reportgroup')),
            ],
            options={
                'ordering': ['organization_id', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_shared', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account_hierarchy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_templates', to='finance.accounthierarchy')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_report_templates', to=settings.AUTH_USER_MODEL)),
                ('default_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_report_templates', to='finance.branch')),
                ('default_cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_report_templates', to='finance.costcenter')),
                ('default_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_report_templates', to='finance.department')),
                ('default_legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_report_templates', to='finance.legalentity')),
                ('default_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_report_templates', to='finance.project')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='finance.reportgroup')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='finance.organization')),
            ],
            options={
                'ordering': ['organization_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportRunSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_data', models.JSONField(default=dict)),
                ('data_as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_hash', models.CharField(blank=True, max_length=128)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_snapshots', to='finance.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_snapshots', to='finance.department')),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_snapshots', to='finance.legalentity')),
                ('run_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_snapshots', to=settings.AUTH_USER_MODEL)),
                ('run_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_snapshots', to='finance.fiscalperiod')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='finance.reporttemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=64)),
                ('data_type', models.CharField(choices=[('actuals', 'Actuals'), ('scenario', 'Scenario/version'), ('variance', 'Variance'), ('mixed', 'Actuals plus scenario')], max_length=16)),
                ('variance_as_percentage', models.BooleanField(default=False)),
                ('period_from_offset', models.IntegerField(default=0)),
                ('period_to_offset', models.IntegerField(default=0)),
                ('prior_year', models.BooleanField(default=False)),
                ('fiscal_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_columns', to='finance.fiscalperiod')),
                ('mixed_cutover_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mixed_report_columns', to='finance.fiscalperiod')),
                ('scenario_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_columns', to='finance.scenarioversion')),
                ('variance_base_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variance_base_usages', to='finance.reportcolumn')),
                ('variance_compare_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variance_compare_usages', to='finance.reportcolumn')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='finance.reporttemplate')),
            ],
            options={
                'ordering': ['template_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanningSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approval_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planning_submission', to='finance.approvalrequest')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planning_submissions', to='finance.branch')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planning_submissions', to='finance.workflowstep')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_planning_submissions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planning_submissions', to='finance.department')),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planning_submissions', to='finance.legalentity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_submissions', to='finance.organization')),
                ('scenario_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_submissions', to='finance.scenarioversion')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_submissions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_submissions', to='finance.workflowdefinition')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('scenario_version', 'legal_entity', 'branch', 'department'), name='uniq_planning_submission_scope', nulls_distinct=False)],
            },
        ),
        migrations.AddConstraint(
            model_name='reportcolumnmodel',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_report_column_model_name_org'),
        ),
        migrations.AddConstraint(
            model_name='reportcolumnmodelitem',
            constraint=models.UniqueConstraint(fields=('column_model', 'sort_order'), name='uniq_report_column_model_item_order'),
        ),
        migrations.AddConstraint(
            model_name='reportcolumnmodelitem',
            constraint=models.CheckConstraint(condition=models.Q(('period_from_offset__lte', models.F('period_to_offset'))), name='report_column_model_item_period_order'),
        ),
        migrations.AddConstraint(
            model_name='reportgroup',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_report_group_name_org'),
        ),
        migrations.AddConstraint(
            model_name='reporttemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_report_template_name_org'),
        ),
        migrations.AddConstraint(
            model_name='reportcolumn',
            constraint=models.UniqueConstraint(fields=('template', 'sort_order'), name='uniq_report_column_order'),
        ),
        migrations.AddConstraint(
            model_name='reportcolumn',
            constraint=models.CheckConstraint(condition=models.Q(('period_from_offset__lte', models.F('period_to_offset'))), name='report_column_period_order'),
        ),
    ]
