{{ config(materialized='table') }}

select
    journal_line_id,
    ingestion_run_id,
    source_system,
    source_entity,
    source_record_id,
    source_line_id,
    source_legal_entity_code,
    document_number,
    line_number,
    posting_date,
    document_date,
    to_char(posting_date, 'YYYYMMDD')::integer as date_key,
    description,
    source_account_code,
    source_branch_code,
    source_department_code,
    source_cost_center_code,
    source_profit_center_code,
    source_business_unit_code,
    source_project_code,
    source_counterparty_code,
    currency_code,
    debit_amount,
    credit_amount,
    debit_amount - credit_amount as signed_amount,
    reporting_currency_code,
    reporting_debit_amount,
    reporting_credit_amount,
    source_created_at,
    source_updated_at,
    ingested_at,
    record_hash,
    created_at,
    updated_at
from {{ ref('stg_journal_lines') }}
where is_deleted is not true