{{ config(materialized='table') }}

select
    invoice_id,
    invoice_line_id,
    organization_id,
    legal_entity_id,
    invoice_direction,
    supplier_id,
    customer_id,
    invoice_number,
    invoice_date,
    due_date,
    currency_id,
    currency_code,
    invoice_status,
    line_number,
    line_description,
    entity_account_id,
    group_account_id,
    branch_id,
    department_id,
    cost_center_id,
    profit_center_id,
    project_id,
    tax_code_id,
    quantity,
    unit_price,
    net_amount,
    tax_amount,
    gross_amount,
    source_system,
    source_entity,
    source_record_id,
    record_hash,
    created_at,
    updated_at
from {{ ref('int_invoices_enriched') }}