select
    id as expense_id,
    source_system,
    source_entity,
    source_record_id,
    record_hash,
    amount,
    upper(trim(currency)) as currency_code,
    currency_master_id,
    description,
    expense_date,
    legal_entity_id,
    branch_id,
    department_id,
    entity_account_id,
    group_account_id,
    cost_center_id,
    profit_center_id,
    business_unit_id,
    project_id,
    is_deleted,
    ingested_at,
    source_created_at,
    source_updated_at,
    created_at,
    updated_at
from {{ source('postgres_app', 'finance_expense') }}
