select
    id as journal_line_id,
    ingestion_run_id,
    source_system,
    source_entity,
    source_record_id,
    source_line_id,
    nullif(trim(source_legal_entity_code), '') as source_legal_entity_code,
    nullif(trim(document_number), '') as document_number,
    line_number,
    posting_date,
    document_date,
    nullif(trim(description), '') as description,
    trim(source_account_code) as source_account_code,
    nullif(trim(source_branch_code), '') as source_branch_code,
    nullif(trim(source_department_code), '') as source_department_code,
    nullif(trim(source_cost_center_code), '') as source_cost_center_code,
    nullif(trim(source_profit_center_code), '') as source_profit_center_code,
    nullif(trim(source_business_unit_code), '') as source_business_unit_code,
    nullif(trim(source_project_code), '') as source_project_code,
    nullif(trim(source_counterparty_code), '') as source_counterparty_code,
    upper(trim(currency)) as currency_code,
    debit_amount,
    credit_amount,
    upper(nullif(trim(reporting_currency), '')) as reporting_currency_code,
    reporting_debit_amount,
    reporting_credit_amount,
    source_created_at,
    source_updated_at,
    ingested_at,
    record_hash,
    is_deleted,
    created_at,
    updated_at
from {{ source('postgres_app', 'finance_rawjournalline') }}